# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH:$HOME/.local

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Themes
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Personal Stuff


source "$HOME/.dotfiles/linux_mac/zshrc/config/env.zsh"
source "$HOME/.dotfiles/linux_mac/zshrc/config/aliases.zsh"

#if [[ "$(uname -s)" == 'Linux' ]]; then
#  source "$ZDOTDIR/linux.zsh"
#elif [[ "$(uname -s)" == 'Darwin' ]]; then
#  source "$ZDOTDIR/mac.zsh"
#fi

