# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Themes
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Personal Stuff

export PATH=$HOME/.dotfiles/bin:$PATH
source "$HOME/.dotfiles/config/env.zsh"
source "$HOME/.dotfiles/config/aliases.zsh"

#if [[ "$(uname -s)" == 'Linux' ]]; then
#  source "$ZDOTDIR/linux.zsh"
#elif [[ "$(uname -s)" == 'Darwin' ]]; then
#  source "$ZDOTDIR/mac.zsh"
#fi

